Release_TPM_Data: Release_TPM_Data.o
	gcc -o Release_TPM_Data Release_TPM_Data.o -ltspi
Release_TPM_Data.o: Release_TPM_Data.c
	gcc -c Release_TPM_Data.c

clean:
	rm -f Release_TPM_Data Release_TPM_Data.o
